//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenSwap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenSwap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation duration:.
        /// </summary>
        public static string AnimationDuration {
            get {
                return ResourceManager.GetString("AnimationDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All windows shortcut:.
        /// </summary>
        public static string AllWindowsShortcut {
            get {
                return ResourceManager.GetString("AllWindowsShortcut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top window only shortcut:.
        /// </summary>
        public static string TopWindowOnlyShortcut {
            get {
                return ResourceManager.GetString("TopWindowOnlyShortcut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to register the shortcut key combo..
        /// </summary>
        public static string MessageKeyNotRegistered {
            get {
                return ResourceManager.GetString("MessageKeyNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shortcut key combo was registered successfully..
        /// </summary>
        public static string MessageKeyRegistered {
            get {
                return ResourceManager.GetString("MessageKeyRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This shortcut is already active..
        /// </summary>
        public static string MessageKeyAlreadyBound {
            get {
                return ResourceManager.GetString("MessageKeyAlreadyBound", resourceCulture);
            }
        }

        public static string MonitorConfigurationChanged {
            get {
                return ResourceManager.GetString("MonitorConfigurationChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenSwap.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TrayOff {
            get {
                object obj = ResourceManager.GetObject("TrayOff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TrayOn {
            get {
                object obj = ResourceManager.GetObject("TrayOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static string TrayTip {
            get {
                return ResourceManager.GetString("TrayTip", resourceCulture);
            }
        }

        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }

        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }

        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }

        public static string Displays {
            get {
                return ResourceManager.GetString("Displays", resourceCulture);
            }
        }

        public static string DisplaysHint {
            get {
                return ResourceManager.GetString("DisplaysHint", resourceCulture);
            }
        }

        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }

        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }

        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }

        public static string MainDisplayTooltip {
            get {
                return ResourceManager.GetString("MainDisplayTooltip", resourceCulture);
            }
        }

        public static string SetMainDisplayTooltip {
            get {
                return ResourceManager.GetString("SetMainDisplayTooltip", resourceCulture);
            }
        }
    }
}
